services:
  db:
    container_name: db
    image: mysql:8
    restart: always
    env_file:
      - .env
    shm_size: 128mb
    networks:
      backend:
        ipv4_address: 172.20.0.10

  web:
    container_name: web
    depends_on:
      - db
    image: web-app:latest
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.python
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - DB_HOST=172.20.0.10
      - DB_NAME=${MYSQL_DATABASE}
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
    env_file:
      - .env
      - .env.homework
    ports:
      - 5000:5000
    networks:
      backend:
        ipv4_address: 172.20.0.5
